// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhrPAUr4YZSch7LuC1YI02n-Kcev8ihuw',
    appId: '1:750104499327:web:3c01be7d93348812211b4a',
    messagingSenderId: '750104499327',
    projectId: 'adityas-first-flutter-project',
    authDomain: 'adityas-first-flutter-project.firebaseapp.com',
    storageBucket: 'adityas-first-flutter-project.appspot.com',
    measurementId: 'G-EC1RZGMV2S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzUnD7YxMzF9hLNGa_7whr7CKgKYagKqo',
    appId: '1:750104499327:android:9c0d20eb721a3c98211b4a',
    messagingSenderId: '750104499327',
    projectId: 'adityas-first-flutter-project',
    storageBucket: 'adityas-first-flutter-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPm206ZYk40be7KKqIF_yUgUxnwaQaOMM',
    appId: '1:750104499327:ios:6ed8234e5b2561eb211b4a',
    messagingSenderId: '750104499327',
    projectId: 'adityas-first-flutter-project',
    storageBucket: 'adityas-first-flutter-project.appspot.com',
    iosBundleId: 'com.example.firstProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPm206ZYk40be7KKqIF_yUgUxnwaQaOMM',
    appId: '1:750104499327:ios:44e110be6dfdd235211b4a',
    messagingSenderId: '750104499327',
    projectId: 'adityas-first-flutter-project',
    storageBucket: 'adityas-first-flutter-project.appspot.com',
    iosBundleId: 'com.example.firstProject.RunnerTests',
  );
}
